### PR TITLE
Fix #223 and make some other changes

### LINKED ISSUE #223: "System.Reflection.TargetParameterCountException : Parameter count mismatch." exception on complex model with list of lists + IgnoreCollectionOrder = true
Hello!

I tried to another complex case to compare object with list of lists (yeah, that's another weird model but I need such objects for my internal tests).

I created minimal gist with example [here](https://gist.github.com/Vasar007/c5a7bd4aa8c5e26961d692d079c9cae5).

Library version: 4.72.0 (with fix for #222)

Stacktrace:
```
System.Reflection.TargetParameterCountException : Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.GetMatchIndex(ComparisonResult result, List`1 spec, Object currentObject)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareOutOfOrder(CompareParms parms, Boolean reverseCompare)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareEnumeratorIgnoreOrder(CompareParms parms, Boolean countsDifferent)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
   at Sample.Tests.GenericCollections.CompareObjects(GenericCollections other) in C:\Users\vasily.vasilyev\source\repos\TestProject\TestProject\Tests\Veeam.CloudBackup.Tests.Common\GenericCollections.cs:line 127
   at Sample.Tests.Tests.ShowTheErrorDictAndList() in C:\Users\vasily.vasilyev\source\repos\TestProject\TestProject\Tests\Veeam.CloudBackup.Tests.Common\Tests.cs:line 42

```

**Important moment: I set `IgnoreCollectionOrder` to `true`. `false` value works without any issues.**

So, it looks like library tries to get value of property and does not specified `index` parameter.

### PR DESCRIPTION
**Pull request by Vasar007**
List of changes:

- CompareLogic now ignores invalid configs in setter;
- ListComparer ignore IgnoreCollectionOrder flag contains nested collections (otherwise, we can get an reflection error);
- Added new tests for indexers and IgnoreCollectionOrder;

### CODE REVIEW

File: Compare-NET-Objects/CompareLogic.cs [hunk 1]
```diff
@@ -124,12 +126,12 @@ public class CompareLogic : ICompareLogic
...
         {
-            get { return _config;}
+            get => _config;
             set
             {
-                _config = value; 
-                VerifyConfig verifyConfig = new VerifyConfig();
+                var verifyConfig = new VerifyConfig();
                 verifyConfig.Verify(value);
+                _config = value;
```
Comment (Vasar007) [inline Compare-NET-Objects/CompareLogic.cs:134]: We should set config after validation. Otherwise, the invalid value can be used.

File: Compare-NET-Objects/IgnoreOrderTypes/IgnoreOrderLogic.cs [hunk 2]
```diff
@@ -236,6 +234,15 @@ private string GetMatchIndex(ComparisonResult result, List<string> spec, object
                         $"Invalid CollectionMatchingSpec.  No such property {item} for type {currentObject.GetType().Name} ");
                 }
 
+                // Ensure that we will not compare indexer property.
+                var indexParameters = info.GetIndexParameters();
```
Comment (Vasar007) [inline Compare-NET-Objects/IgnoreOrderTypes/IgnoreOrderLogic.cs:238]: I added explicit check on indexers to replace reflection error with our own exception.

File: Compare-NET-Objects/TypeComparers/IndexerComparer.cs [hunk 3]
```diff
@@ -123,38 +123,25 @@ public void CompareIndexer(CompareParms parms, PropertyEntity info, PropertyEnti
...
-            var type = info.ReflectedType;
-            var type2 = secondObjectInfo.ReflectedType;
-#else
-            var type = info.DeclaringType;
-            var type2 = secondObjectInfo.DeclaringType;
-#endif
-            if (type == null || type2 == null)
-                throw new ArgumentNullException("info");
-
-            int indexerCount1 = (int)type.GetProperty("Count").GetGetMethod().Invoke(parms.Object1, new object[] { });
```
Comment (Vasar007) [inline Compare-NET-Objects/TypeComparers/IndexerComparer.cs:141]: Do not know why we should use the reflection twice. We have alredy used reflection before to get this values.

File: Compare-NET-Objects/TypeComparers/ListComparer.cs [hunk 4]
```diff
@@ -64,8 +65,12 @@ public override void CompareType(CompareParms parms)
 
                 bool countsDifferent = ListsHaveDifferentCounts(parms);
 
-                if (parms.Config.IgnoreCollectionOrder && !ChildIsListOrDictionary(parms))
+                // If items is collections, need to use default compare logic, not ignore order logic.
+                // We cannot ignore order for nested collections because we will get an reflection exception.
+                // May be need to display some warning or write about this behavior in documentation.
+                if (parms.Config.IgnoreCollectionOrder && !ChildShouldBeComparedWithoutOrder(parms))
                 {
+                    // TODO: allow IndexerComparer to works with types (now it works only with properties).
```
Comment (Vasar007) [inline Compare-NET-Objects/TypeComparers/ListComparer.cs:73]: I decided to extend original check. Full support of collection with nested collection is not that simple as I thing. I suggest this feature for the future releases :)

File: Compare-NET-Objects/TypeComparers/ListComparer.cs [hunk 5]
```diff
@@ -146,17 +151,48 @@ private bool ListsHaveDifferentCounts(CompareParms parms)
             return false;
         }
 
-        private bool ChildIsListOrDictionary(CompareParms parms)
+        private bool ChildShouldBeComparedWithoutOrder(CompareParms parms)
```
Comment (Vasar007) [inline Compare-NET-Objects/TypeComparers/ListComparer.cs:154]: This check does not work for my case because nested collection starts with null. Now we take into account all values in collection.

File: Compare-NET-Objects/TypeComparers/PropertyComparer.cs [hunk 6]
```diff
@@ -237,7 +237,7 @@ private static List<PropertyEntity> HandleInterfaceMembers(CompareParms parms, o
             return currentProperties;
         }
 
-        private static List<PropertyEntity> HandleDynamicObject(ComparisonConfig config, object objectValue, Type objectType)
+        private static List<PropertyEntity> HandleDynamicObject(object objectValue, Type objectType)
```
Comment (Vasar007) [inline Compare-NET-Objects/TypeComparers/PropertyComparer.cs:240]: I removed unused parameter for private method.

File: Compare-NET-Objects/VerifyConfig.cs [hunk 7]
```diff
@@ -37,16 +37,15 @@ public void VerifySpec(ComparisonConfig config)
                     string msg = string.Format(
                         "Collection Matching Spec Type {0} should be a class, not a List.  Expected something like Customer, not List<Customer>.  See https://github.com/GregFinzer/Compare-Net-Objects/wiki/Comparing-Lists-of-Different-Lengths",
                         kvp.Key.Name);
-                    throw new Exception(msg);
+                    throw new ArgumentException(msg, nameof(config));
```
Comment (Vasar007) [inline Compare-NET-Objects/VerifyConfig.cs:40]: Change type of an exception to provide caller more information about exception. I think that using raw Exception is not that good in most cases. We should use the specific one if it is possible.

**Comment by GregFinzer** [comment]
Thanks so much

**Comment by Vasar007** [comment]
When do you plan to publish new package with latest fixes of #222 and #223?

**Comment by GregFinzer** [comment]
Sometime before Monday March 22nd.
